// NOTE: This is generated by 'w3 codegen', DO NOT MODIFY

import { Uniswap, IUniswap } from "./uniswap";
import { Client, ExtensionConfig, BasePolywrapDappConfig, BasePolywrapDapp } from "@web3api/core-js";

export interface PolywrapDappConfig extends BasePolywrapDappConfig {
  uniswap?: ExtensionConfig
}

export class PolywrapDapp implements BasePolywrapDapp {

  readonly client: Client;
  readonly uniswap: IUniswap;

  constructor(client: Client, config?: PolywrapDappConfig) {
    this.client = client;
    this.uniswap = new Uniswap(this.client, config?.uniswap);
  }
}
