// NOTE: This is generated by 'w3 codegen', DO NOT MODIFY

// @ts-noCheck
import {
  UInt,
  UInt8,
  UInt16,
  UInt32,
  Int,
  Int8,
  Int16,
  Int32,
  Bytes,
  BigInt,
  Json,
  String,
  Boolean
} from "../baseTypes";
import {
  Currency,
  Token,
  Route,
  Tick,
  TickListDataProvider,
  Pool,
  Trade,
  TokenAmount,
  TradeSwap,
  Price,
  SwapOptions,
  PermitOptions,
  FeeOptions,
  MethodParameters,
  GasOptions,
  NextTickResult,
  PoolChangeResult,
  TradeRoute,
  IncentiveKey,
  ClaimOptions,
  FullWithdrawOptions,
  QuoteOptions,
  CommonAddLiquidityOptions,
  AddLiquidityOptions,
  SafeTransferOptions,
  CollectOptions,
  NFTPermitOptions,
  RemoveLiquidityOptions,
  BestTradeOptions,
  Position,
  MintAmounts,
  ChainIdEnum,
  ChainIdString,
  ChainId,
  FeeAmountEnum,
  FeeAmountString,
  FeeAmount,
  TradeTypeEnum,
  TradeTypeString,
  TradeType,
  PermitVEnum,
  PermitVString,
  PermitV,
  RoundingEnum,
  RoundingString,
  Rounding,
  Ethereum_Connection,
  Ethereum_TxOverrides,
  Ethereum_TxResponse,
  Ethereum_Access,
  Ethereum_TxReceipt,
  Ethereum_Log,
  Ethereum_TxRequest,
  Ethereum_StaticTxResult,
  Ethereum_EventNotification,
  Ethereum_Network,
  ERC20_Ethereum_Connection,
  Ethereum_Mutation,
  Ethereum_Query,
  SHA3_Query,
  EthersSolidity_Query,
  ERC20_Query,
  Subgraph_Query,
} from "./types";

export interface Input_swap extends Record<string, unknown> {
  tokenIn: Token;
  tokenOut: Token;
  amount: BigInt;
  tradeType: TradeType;
  feeAmount: FeeAmount;
  swapOptions: SwapOptions;
  gasOptions: GasOptions;
}

export interface Input_pool extends Record<string, unknown> {
  tokenA: Token;
  tokenB: Token;
  feeAmount: FeeAmount;
  gasOptions: GasOptions;
}

export interface Input_execSwap extends Record<string, unknown> {
  trades: Array<Trade>;
  swapOptions: SwapOptions;
  gasOptions: GasOptions;
}

export interface Input_execPool extends Record<string, unknown> {
  pool: Pool;
  gasOptions: GasOptions;
}

export interface Input_execCall extends Record<string, unknown> {
  parameters: MethodParameters;
  address: String;
  chainId: ChainId;
  gasOptions: GasOptions;
}

export interface Input_approve extends Record<string, unknown> {
  token: Token;
  amount?: BigInt | null;
  gasOptions: GasOptions;
}


