// NOTE: This is generated by 'w3 codegen', DO NOT MODIFY

// @ts-noCheck
import { BigInt } from '../baseTypes'
import { ChainId, FeeAmount, GasOptions, MethodParameters, Pool, SwapOptions, Token, Trade, TradeType } from './types'

export interface Input_swap extends Record<string, unknown> {
  tokenIn: Token
  tokenOut: Token
  amount: BigInt
  tradeType: TradeType
  feeAmount: FeeAmount
  swapOptions: SwapOptions
  gasOptions: GasOptions
}

export interface Input_pool extends Record<string, unknown> {
  tokenA: Token
  tokenB: Token
  feeAmount: FeeAmount
  gasOptions: GasOptions
}

export interface Input_execSwap extends Record<string, unknown> {
  trades: Array<Trade>
  swapOptions: SwapOptions
  gasOptions: GasOptions
}

export interface Input_execPool extends Record<string, unknown> {
  pool: Pool
  gasOptions: GasOptions
}

export interface Input_execCall extends Record<string, unknown> {
  parameters: MethodParameters
  address: string
  chainId: ChainId
  gasOptions: GasOptions
}

export interface Input_approve extends Record<string, unknown> {
  token: Token
  amount?: BigInt | null
  gasOptions: GasOptions
}
